# Generated by Django 6.0.1 on 2026-05-23 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_booth_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='operate_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booth',
            name='table_max_cnt',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
