# Generated by Django 6.0.1 on 2026-05-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_table_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
