# Generated by Django 6.0.2 on 2026-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('COOKING', '조리중'), ('COOKED', '조리완료'), ('SERVING', '서빙중'), ('SERVED', '서빙완료'), ('CANCELLED', '취소')], max_length=20),
        ),
    ]
