"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers
import os
import environ


BASE_DIR = Path(__file__).resolve().parent.parent
# .env 파일 로드
env = environ.Env(
    DEBUG=(bool, False),
    ENVIRONMENT=(str, 'local')
)
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경 설정 (local / development / production)
ENVIRONMENT = env('ENVIRONMENT')
IS_LOCAL = ENVIRONMENT == 'local'
IS_DEVELOPMENT = ENVIRONMENT == 'development'
IS_PRODUCTION = ENVIRONMENT == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')  # .env에서 필수로 설정 필요

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# 환경별 ALLOWED_HOSTS 설정 (.env에서 로드)
def get_allowed_hosts():
    """
    ENVIRONMENT에 따라 .env에서 ALLOWED_HOSTS를 로드합니다.
    쉼표로 구분된 호스트 목록을 리스트로 변환합니다.
    """
    if IS_LOCAL:
        hosts_str = env('ALLOWED_HOSTS_LOCAL')
    elif IS_DEVELOPMENT:
        # Development: 개발 도메인 + 로컬 호스트 모두 허용
        dev = env('ALLOWED_HOSTS_DEV')
        local = env('ALLOWED_HOSTS_LOCAL')
        hosts_str = f"{dev},{local}"
    else:  # IS_PRODUCTION
        hosts_str = env('ALLOWED_HOSTS_PRODUCTION')

    hosts = [host.strip() for host in hosts_str.split(',')]
    # Docker 내부 healthcheck는 localhost로 요청하므로 항상 포함
    for h in ['localhost', '127.0.0.1']:
        if h not in hosts:
            hosts.append(h)
    return hosts

ALLOWED_HOSTS = get_allowed_hosts() 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #apps
    'authentication',
    'core',
    'booth',
    'table',
    'cart',
    'coupon',
    'menu',
    'order',

    # S3
    'storages',

    #drf
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Channels (WebSocket)
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'authentication.middleware.JWTCookieMiddleware',   # 쿠키 → 헤더 변환
    'authentication.middleware.StaleCookiePurgeMiddleware',  # 옛 도메인 잔재 쿠키 일소
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'  # WebSocket용 (Daphne)


REDIS_HOST = env('REDIS_HOST')
REDIS_PORT = env('REDIS_PORT')
REDIS_PASSWORD = env('REDIS_PASSWORD')

import sys
if 'PYTEST_CURRENT_TEST' in os.environ:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    if REDIS_PASSWORD:
        redis_url = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
    else:
        redis_url = f"redis://{REDIS_HOST}:{REDIS_PORT}"
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
            },
        },
    }

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': env('DB_USER', default=''),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default=''),
        'PORT': env('DB_PORT', default=''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.jwt_cookie_authentication.JWTCookieAuthentication',  # JWT 쿠키 + CSRF
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler',
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),

    # 쿠키 기반 인증 설정
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': not IS_LOCAL,  # local 제외 HTTPS 환경에서 Secure
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'None' if IS_DEVELOPMENT else 'Lax',  # dev: cross-origin 쿠키 전송 허용
    'AUTH_COOKIE_DOMAIN': None,  # host-only: 서브도메인 간 쿠키 누적/충돌 방지
}

# Logging 설정
_file_handlers = {} if IS_LOCAL else {
    'file': {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': '/app/logs/django.log',
        'maxBytes': 1024 * 1024 * 10,  # 10MB
        'backupCount': 5,
        'formatter': 'verbose',
        'encoding': 'utf-8',
        'level': 'DEBUG',
    },
    'file_error': {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': '/app/logs/error.log',
        'maxBytes': 1024 * 1024 * 5,   # 5MB
        'backupCount': 3,
        'formatter': 'verbose',
        'encoding': 'utf-8',
        'level': 'ERROR',
    },
}
_file_handler = [] if IS_LOCAL else ['file']
_file_error_handler = [] if IS_LOCAL else ['file_error']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        **_file_handlers,
    },

    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'] + _file_handler,
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'] + _file_error_handler,
            'level': 'WARNING',  # 4xx=WARNING, 5xx=ERROR 자동 분류
            'propagate': False,  # django logger 중복 방지
        },
        'channels': {
            'handlers': ['console'] + _file_handler,
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console'] + _file_handler,
            'level': 'DEBUG',
            'propagate': False,
        },
        'booth': {
            'handlers': ['console'] + _file_handler,
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'] + _file_handler,
            'level': 'DEBUG',
            'propagate': False,
        },
        'order': {
            'handlers': ['console'] + _file_handler,
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Silk 프로파일링 설정 (로컬 전용)
if IS_LOCAL:
    INSTALLED_APPS += ['silk']
    MIDDLEWARE.insert(0, 'silk.middleware.SilkyMiddleware')
    SILKY_PYTHON_PROFILER = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# ==========================================
# 미디어 파일 스토리지 (환경별)
# ==========================================

# AWS S3 설정 (Development/Production)
if not IS_LOCAL:
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
    
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

else:
    # 로컬: 파일시스템 사용
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# 환경별 CORS Origins 설정 (.env에서 필수 로드)
def get_cors_origins():
    """
    - IS_LOCAL: CORS_ALLOWED_ORIGINS_LOCAL
    - IS_DEVELOPMENT: CORS_ALLOWED_ORIGINS_DEV + CORS_ALLOWED_ORIGINS_LOCAL
    - IS_PRODUCTION: CORS_ALLOWED_ORIGINS_FRONTEND + CORS_ALLOWED_ORIGINS_BACKEND

    """
    if IS_LOCAL:
        origins_str = env('CORS_ALLOWED_ORIGINS_LOCAL')
    elif IS_DEVELOPMENT:
        dev = env('CORS_ALLOWED_ORIGINS_DEV')
        local = env('CORS_ALLOWED_ORIGINS_LOCAL')
        origins_str = f"{dev},{local}"
    else:  # IS_PRODUCTION
        frontend = env('CORS_ALLOWED_ORIGINS_FRONTEND')
        backend = env('CORS_ALLOWED_ORIGINS_BACKEND')
        origins_str = f"{frontend},{backend}"

    return [origin.strip() for origin in origins_str.split(',')]

CORS_ALLOWED_ORIGINS = get_cors_origins()

if not IS_PRODUCTION:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"https://.*\.netlify\.app",
    ]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'booth-id',
]

# ==========================================
# 보안 설정 (환경별)
# ==========================================
# HTTPS/SSL 설정
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 쿠키 보안 설정
CSRF_COOKIE_NAME = 'csrftoken'              # 쿠키 이름
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not IS_LOCAL)
CSRF_COOKIE_HTTPONLY = False                # JavaScript에서 접근 가능 (React에서 필요)
CSRF_COOKIE_SAMESITE = 'None' if IS_DEVELOPMENT else 'Lax'  # dev: localhost/netlify cross-site 호출 허용
CSRF_COOKIE_DOMAIN = None  # host-only: 서브도메인 간 쿠키 누적/충돌 방지

SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = env.bool('SESSION_COOKIE_HTTPONLY', default=True)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = None  # host-only: 서브도메인 간 쿠키 누적/충돌 방지


# CSRF 설정
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'       
CSRF_COOKIE_AGE = 31449600  # 1년
SESSION_COOKIE_AGE = 1209600  # 2주

CSRF_TRUSTED_ORIGINS = get_cors_origins()

# 보안 헤더
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0  # 1년 (프로덕션만)
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION

# XSS 보호
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "'unsafe-inline'"),  # React에서 필요
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "https:"),
    "font-src": ("'self'",),
    "connect-src": ("'self'", "*.d-order.store", "localhost:*", "127.0.0.1:*"),
} if IS_PRODUCTION else None

# Clickjacking 보호
X_FRAME_OPTIONS = 'DENY'

CUSTOMER_FRONT_BASE_URL = env('CUSTOMER_FRONT_BASE_URL',default='localhost:3000')