# Generated by Django 6.0.1 on 2026-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_started_at_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tablegroup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tableusage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
